table dVendedores
	lineageTag: 396dc5cb-0e59-4a23-b70a-58520328763f

	column 'Id Vendedor'
		dataType: int64
		formatString: 0
		lineageTag: 572e6255-2191-445b-85ef-75826c6abe68
		summarizeBy: none
		sourceColumn: Id Vendedor

		annotation SummarizationSetBy = Automatic

	column Vendedor
		dataType: string
		lineageTag: 28b7beff-c270-4a77-8414-9def3902e6d9
		summarizeBy: none
		sourceColumn: Vendedor

		annotation SummarizationSetBy = Automatic

	column 'URL Foto'
		dataType: string
		lineageTag: 7a559965-76ee-423c-a495-1e896444158a
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: URL Foto

		annotation SummarizationSetBy = Automatic

	column Gerente
		dataType: string
		lineageTag: 0b904430-494e-4b36-83a1-dc04b6b960fc
		summarizeBy: none
		sourceColumn: Gerente

		annotation SummarizationSetBy = Automatic

	column 'URL Foto Corpo'
		dataType: string
		lineageTag: 631d4793-ae08-43f7-b331-daf2dc5d4b8f
		summarizeBy: none
		sourceColumn: URL Foto Corpo

		annotation SummarizationSetBy = Automatic

	partition dVendedores-ad9209f5-dc6e-4612-baa4-5f8a02abd9e9 = m
		mode: import
		queryGroup: Dimensões
		source =
				let
				    Fonte = Excel.Workbook(File.Contents(Caminho_Dimensoes & "\Dimensões.xlsx"), null, true),
				    Vendedores_Table = Fonte{[Item="Vendedores",Kind="Table"]}[Data],
				    ColunaRenomeada = Table.RenameColumns(Vendedores_Table,{{"URL Foto Inteira", "URL Foto Corpo"}}),
				    TipagemDados = Table.TransformColumnTypes(ColunaRenomeada,{{"Id Vendedor", Int64.Type}, {"Vendedor", type text}, {"URL Foto", type text}, {"Gerente", type text}, {"URL Foto Corpo", type text}})
				in
				    TipagemDados

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

