{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.139.2054.0 (24.12)+334ca1c95b576cc53924655643b0d36f21caac55"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"fVendas\",\"dPagamento\",\"dCidades\",\"dClientes\",\"dProdutos\",\"dStatus\",\"dUnidades\",\"dVendedores\",\"fMetas\",\"dCalendario\",\"Caminho_Extracao\",\"Caminho_Dimensoes\",\"Caminho_Meta\",\"_Medidas\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "dCidades",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Excel.Workbook(File.Contents(Caminho_Dimensoes & \"\\Dimensões.xlsx\"), null, true),",
          "    Cidades_Table = Fonte{[Item=\"Cidades\",Kind=\"Table\"]}[Data],",
          "    RemoverEspaçosColunaEstado = Table.TransformColumns(Cidades_Table,{{\"Estado\", Text.Trim, type text}}),",
          "    TipagemDados = Table.TransformColumnTypes(RemoverEspaçosColunaEstado,{{\"Id Cidade\", Int64.Type}, {\"Cidade\", type text}, {\"UF\", type text}, {\"Estado\", type text}})",
          "in",
          "    TipagemDados"
        ],
        "kind": "m",
        "lineageTag": "d3f37f5a-9cba-4a50-9c62-32db5582c5e3",
        "queryGroup": "Auxiliares"
      },
      {
        "name": "Caminho_Extracao",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"D:\\Curso\\Jefferson Curso Completo\\Base Dados\\Extrações\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "2747c0ba-a302-4812-bdbe-bd561a0d13e0"
      },
      {
        "name": "Caminho_Dimensoes",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"D:\\Curso\\Jefferson Curso Completo\\Base Dados\\Dimensões\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "d6a58aa4-ecb7-4ce6-90e3-30f15eb7ec48"
      },
      {
        "name": "Caminho_Meta",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"D:\\Curso\\Jefferson Curso Completo\\Base Dados\\Metas\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "45a9cb35-ec05-4519-bf97-bc1012799606"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Fatos"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Dimensões"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "Auxiliares"
      }
    ],
    "relationships": [
      {
        "name": "f55b03a9-fe7c-48f8-b7e0-60962ccbd1a5",
        "fromColumn": "Id Cliente",
        "fromTable": "fVendas",
        "toColumn": "Id Cliente",
        "toTable": "dClientes"
      },
      {
        "name": "f626dabc-54a7-4519-9756-739f39ca5256",
        "fromColumn": "Id Unidade",
        "fromTable": "fVendas",
        "toColumn": "Id Unidade",
        "toTable": "dUnidades"
      },
      {
        "name": "a960b40d-8bab-48a5-affa-9b4c83eaf146",
        "fromColumn": "Id Status",
        "fromTable": "fVendas",
        "toColumn": "Id Status",
        "toTable": "dStatus"
      },
      {
        "name": "bf8558a7-984c-497e-b52a-79923378ecd8",
        "fromColumn": "Id Vendedor",
        "fromTable": "fMetas",
        "toColumn": "Id Vendedor",
        "toTable": "dVendedores"
      },
      {
        "name": "e30f9788-44f7-4aee-9087-f4d7ad315c36",
        "fromColumn": "Id Produto",
        "fromTable": "fVendas",
        "toColumn": "Id Produto",
        "toTable": "dProdutos"
      },
      {
        "name": "c84b7752-27fe-434e-82e8-4f64e3c33dc6",
        "fromColumn": "Id Vendedor",
        "fromTable": "fVendas",
        "toColumn": "Id Vendedor",
        "toTable": "dVendedores"
      },
      {
        "name": "bc5d498a-fd7a-492a-a8ac-ac6c32b82a2a",
        "fromColumn": "Id Pgto",
        "fromTable": "fVendas",
        "toColumn": "Id Pagamento",
        "toTable": "dPagamento"
      },
      {
        "name": "d7b8ed39-b563-4f2d-4b29-e129ca7e9639",
        "fromColumn": "Data Pedido",
        "fromTable": "fVendas",
        "toColumn": "Id Data",
        "toTable": "dCalendario"
      },
      {
        "name": "8d3886e4-6177-0b31-357f-2b7cbf95a786",
        "fromColumn": "Data Envio",
        "fromTable": "fVendas",
        "isActive": false,
        "toColumn": "Id Data",
        "toTable": "dCalendario"
      },
      {
        "name": "771a454e-5923-d152-2b8b-7f16b937015b",
        "fromColumn": "Data",
        "fromTable": "fMetas",
        "toColumn": "Id Data",
        "toTable": "dCalendario"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "fVendas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "Data Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "8fb393f9-6a31-4014-ac4f-898b724ea913",
            "sourceColumn": "Data Pedido",
            "summarizeBy": "none"
          },
          {
            "name": "Data Envio",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "7dfcf63c-37ee-4d8c-a6cf-1fe414e98ca5",
            "sourceColumn": "Data Envio",
            "summarizeBy": "none"
          },
          {
            "name": "Num Venda",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1b8cb0f0-65e9-4459-83a2-319c3b2e3125",
            "sourceColumn": "Num Venda",
            "summarizeBy": "none"
          },
          {
            "name": "Id Produto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3f83790a-e186-48e0-aec6-1063c58fc207",
            "sourceColumn": "Id Produto",
            "summarizeBy": "none"
          },
          {
            "name": "Id Vendedor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1b73bc77-f58c-43cd-9918-138bb19c78be",
            "sourceColumn": "Id Vendedor",
            "summarizeBy": "none"
          },
          {
            "name": "Id Cliente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c09576b8-a843-41a2-83bf-10f4588c9244",
            "sourceColumn": "Id Cliente",
            "summarizeBy": "none"
          },
          {
            "name": "Id Unidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7305a7da-9904-4511-a904-3196f5299911",
            "sourceColumn": "Id Unidade",
            "summarizeBy": "none"
          },
          {
            "name": "Id Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c031e2bd-544a-42a7-b7d9-4002fa00a935",
            "sourceColumn": "Id Status",
            "summarizeBy": "none"
          },
          {
            "name": "Id Pgto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e48f32d7-cea0-4978-8dc0-ac51148c78ba",
            "sourceColumn": "Id Pgto",
            "summarizeBy": "none"
          },
          {
            "name": "Qtde",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a4e92aac-1b5c-421e-9fce-64d7b8f75cc2",
            "sourceColumn": "Qtde",
            "summarizeBy": "sum"
          },
          {
            "name": "Valor Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "14493381-5d7d-4be5-b2d5-96a700ba9c31",
            "sourceColumn": "Valor Unit",
            "summarizeBy": "sum"
          },
          {
            "name": "Custo Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "cf72aa42-a71a-4387-9510-a3cc2fa90192",
            "sourceColumn": "Custo Unit",
            "summarizeBy": "sum"
          },
          {
            "name": "Despesa Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "decimal",
            "formatString": "0",
            "lineageTag": "48c3c771-f9e9-48a9-880c-04fb104f5682",
            "sourceColumn": "Despesa Unit",
            "summarizeBy": "sum"
          },
          {
            "name": "Impostos Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "82a85709-3e5e-48d7-8648-6a25902a4895",
            "sourceColumn": "Impostos Unit",
            "summarizeBy": "sum"
          },
          {
            "name": "Comissão Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "ae0235f6-34f7-4402-8767-c7710c576d6c",
            "sourceColumn": "Comissão Unit",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "ce3764bc-f894-4270-a9e3-ac66e5acc86d",
        "partitions": [
          {
            "name": "fVendas-7f501c7e-a537-49ee-a211-96121f01c700",
            "mode": "import",
            "queryGroup": "Fatos",
            "source": {
              "expression": [
                "let",
                "    Fonte = Excel.Workbook(File.Contents(Caminho_Extracao & \"\\Vendas.xlsx\"), null, true),",
                "    fVendas_Sheet = Fonte{[Item=\"fVendas\",Kind=\"Sheet\"]}[Data],",
                "    LinhasIniciaisRemovidas = Table.SelectRows(fVendas_Sheet, each ([Column3] <> null)),",
                "    CabecalhoPromovido = Table.PromoteHeaders(LinhasIniciaisRemovidas, [PromoteAllScalars=true]),",
                "    PrimeiraColunaRenomeada = Table.RenameColumns(CabecalhoPromovido,{{\"Data\", \"Data Pedido\"}}),",
                "    ColunasRemovidas = Table.SelectColumns(PrimeiraColunaRenomeada,{\"Data Pedido\", \"Data Envio\", \"Num Venda\", \"Id Produto\", \"Id Vendedor\", \"Id Cliente\", \"Id Unidade\", \"Id Status\", \"Id Pgto\", \"Qtde\", \"Valor Unit\", \"Custo Unit\", \"Despesa Unit\", \"Impostos Unit\", \"Comissão Unit\"}),",
                "    TipagemDados = Table.TransformColumnTypes(ColunasRemovidas,{{\"Data Pedido\", type date}, {\"Data Envio\", type date}, {\"Num Venda\", type text}, {\"Id Produto\", Int64.Type}, {\"Id Vendedor\", Int64.Type}, {\"Id Cliente\", Int64.Type}, {\"Id Unidade\", Int64.Type}, {\"Id Status\", Int64.Type}, {\"Id Pgto\", Int64.Type}, {\"Qtde\", Int64.Type}, {\"Valor Unit\", Currency.Type}, {\"Custo Unit\", Currency.Type}, {\"Despesa Unit\", Currency.Type}, {\"Impostos Unit\", Currency.Type}, {\"Comissão Unit\", Currency.Type}})",
                "in",
                "    TipagemDados"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dPagamento",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "Id Pagamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "aacc5b7e-5ed4-4d31-b1e0-ceeb75116ec4",
            "sourceColumn": "Id Pagamento",
            "summarizeBy": "none"
          },
          {
            "name": "Forma de Pagamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "11a6c0f4-cead-4e16-b071-101d5f0305a8",
            "sourceColumn": "Forma de Pagamento",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d09cb269-5b16-4541-89ca-be6bbe02d3fe",
        "partitions": [
          {
            "name": "dPagamento-45f6a09d-5408-4fcb-a156-3ce36c359dca",
            "mode": "import",
            "queryGroup": "Dimensões",
            "source": {
              "expression": [
                "let",
                "    Fonte = Excel.Workbook(File.Contents(Caminho_Dimensoes & \"\\Dimensões.xlsx\"), null, true),",
                "    Pagamento_Table = Fonte{[Item=\"Pagamento\",Kind=\"Table\"]}[Data],",
                "    TipagemDados = Table.TransformColumnTypes(Pagamento_Table,{{\"Id Pagamento\", Int64.Type}, {\"Forma de Pagamento\", type text}})",
                "in",
                "    TipagemDados"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dClientes",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "Id Cliente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ec3e1d8a-9f2b-4583-858f-0bcce3aacb4f",
            "sourceColumn": "Id Cliente",
            "summarizeBy": "none"
          },
          {
            "name": "Cliente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "87372cb9-b83b-4713-9274-2d913da87b76",
            "sourceColumn": "Cliente",
            "summarizeBy": "none"
          },
          {
            "name": "Cidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "01924770-f939-4c18-8398-2e5e836069e5",
            "sourceColumn": "Cidade",
            "summarizeBy": "none"
          },
          {
            "name": "UF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eac22a93-85e1-4edd-970b-b9c598b3bbe6",
            "sourceColumn": "UF",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3077b4c9-4f2e-4a50-a247-f4260eede252",
        "partitions": [
          {
            "name": "dClientes-45ef84c7-1d35-4ccf-a71d-0f3ba0560307",
            "mode": "import",
            "queryGroup": "Dimensões",
            "source": {
              "expression": [
                "let",
                "    Fonte = Excel.Workbook(File.Contents(Caminho_Dimensoes & \"\\Dimensões.xlsx\"), null, true),",
                "    Clientes_Table = Fonte{[Item=\"Clientes\",Kind=\"Table\"]}[Data],",
                "    MesclarConsultasCidades = Table.NestedJoin(Clientes_Table, {\"Id Cidade\"}, dCidades, {\"Id Cidade\"}, \"dCidades\", JoinKind.LeftOuter),",
                "    dCidadesExpandido = Table.ExpandTableColumn(MesclarConsultasCidades, \"dCidades\", {\"Cidade\", \"UF\"}, {\"Cidade\", \"UF\"}),",
                "    RemoverColunaIDCidade = Table.SelectColumns(dCidadesExpandido,{\"Id Cliente\", \"Cliente\", \"Cidade\", \"UF\"}),",
                "    TipagemDados = Table.TransformColumnTypes(RemoverColunaIDCidade,{{\"Id Cliente\", Int64.Type}, {\"Cliente\", type text}, {\"Cidade\", type text}, {\"UF\", type text}})",
                "in",
                "    TipagemDados"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dProdutos",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "Id Produto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3e9c0315-b38c-4736-b7d0-b56bc2eb5cca",
            "sourceColumn": "Id Produto",
            "summarizeBy": "none"
          },
          {
            "name": "Produto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f53ca8fd-0276-4ffa-9428-05f8f966c439",
            "sourceColumn": "Produto",
            "summarizeBy": "none"
          },
          {
            "name": "Categoria",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1e00f31c-b6cf-4477-ac53-1e345ba4b3c3",
            "sourceColumn": "Categoria",
            "summarizeBy": "none"
          },
          {
            "name": "Subcategoria",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ce80e633-63f3-485c-8355-dc4d78023bb0",
            "sourceColumn": "Subcategoria",
            "summarizeBy": "none"
          },
          {
            "name": "Marca",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ecd229b6-f1cd-4aab-a07d-25c134cda97c",
            "sourceColumn": "Marca",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ac541bd4-bdb6-4cc2-9200-a85f58226c53",
        "partitions": [
          {
            "name": "dProdutos-52791452-0570-427e-9770-8f9f216eeb78",
            "mode": "import",
            "queryGroup": "Dimensões",
            "source": {
              "expression": [
                "let",
                "    Fonte = Excel.Workbook(File.Contents(Caminho_Dimensoes & \"\\Dimensões.xlsx\"), null, true),",
                "    Produtos_Table = Fonte{[Item=\"Produtos\",Kind=\"Table\"]}[Data],",
                "    TipagemDados = Table.TransformColumnTypes(Produtos_Table,{{\"Id Produto\", Int64.Type}, {\"Produto\", type text}, {\"Categoria\", type text}, {\"Subcategoria\", type text}, {\"Marca\", type text}})",
                "in",
                "    TipagemDados"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dStatus",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "Id Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a291336f-6ace-452c-8058-669c798540b9",
            "sourceColumn": "Id Status",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9b9b4d20-d115-478f-85ca-89bc2e0a0f99",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5d9b2548-8d53-4085-8a7e-7ccc0ee32b2d",
        "partitions": [
          {
            "name": "dStatus-700e1395-c7fb-425e-aa98-61d87aafecb4",
            "mode": "import",
            "queryGroup": "Dimensões",
            "source": {
              "expression": [
                "let",
                "    Fonte = Excel.Workbook(File.Contents(Caminho_Dimensoes & \"\\Dimensões.xlsx\"), null, true),",
                "    Status_Table = Fonte{[Item=\"Status\",Kind=\"Table\"]}[Data],",
                "    TipagemDados = Table.TransformColumnTypes(Status_Table,{{\"Id Status\", Int64.Type}, {\"Status\", type text}})",
                "in",
                "    TipagemDados"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dUnidades",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "Id Unidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d166ccd0-4949-43e6-930e-7d8fff008fcb",
            "sourceColumn": "Id Unidade",
            "summarizeBy": "none"
          },
          {
            "name": "Unidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "62d98bd6-9d75-439c-9734-600523cc3cbf",
            "sourceColumn": "Unidade",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "527df0f4-5aae-4c5a-aae3-e5fcd8735c48",
        "partitions": [
          {
            "name": "dUnidades-06e92872-ce0d-4437-82a6-23df86366426",
            "mode": "import",
            "queryGroup": "Dimensões",
            "source": {
              "expression": [
                "let",
                "    Fonte = Excel.Workbook(File.Contents(Caminho_Dimensoes & \"\\Dimensões.xlsx\"), null, true),",
                "    Unidades_Table = Fonte{[Item=\"Unidades\",Kind=\"Table\"]}[Data],",
                "    TipagemDados = Table.TransformColumnTypes(Unidades_Table,{{\"Id Unidade\", Int64.Type}, {\"Unidade\", type text}})",
                "in",
                "    TipagemDados"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dVendedores",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "Id Vendedor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "572e6255-2191-445b-85ef-75826c6abe68",
            "sourceColumn": "Id Vendedor",
            "summarizeBy": "none"
          },
          {
            "name": "Vendedor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "28b7beff-c270-4a77-8414-9def3902e6d9",
            "sourceColumn": "Vendedor",
            "summarizeBy": "none"
          },
          {
            "name": "URL Foto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "lineageTag": "7a559965-76ee-423c-a495-1e896444158a",
            "sourceColumn": "URL Foto",
            "summarizeBy": "none"
          },
          {
            "name": "Gerente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b904430-494e-4b36-83a1-dc04b6b960fc",
            "sourceColumn": "Gerente",
            "summarizeBy": "none"
          },
          {
            "name": "URL Foto Corpo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "631d4793-ae08-43f7-b331-daf2dc5d4b8f",
            "sourceColumn": "URL Foto Corpo",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "396dc5cb-0e59-4a23-b70a-58520328763f",
        "partitions": [
          {
            "name": "dVendedores-ad9209f5-dc6e-4612-baa4-5f8a02abd9e9",
            "mode": "import",
            "queryGroup": "Dimensões",
            "source": {
              "expression": [
                "let",
                "    Fonte = Excel.Workbook(File.Contents(Caminho_Dimensoes & \"\\Dimensões.xlsx\"), null, true),",
                "    Vendedores_Table = Fonte{[Item=\"Vendedores\",Kind=\"Table\"]}[Data],",
                "    ColunaRenomeada = Table.RenameColumns(Vendedores_Table,{{\"URL Foto Inteira\", \"URL Foto Corpo\"}}),",
                "    TipagemDados = Table.TransformColumnTypes(ColunaRenomeada,{{\"Id Vendedor\", Int64.Type}, {\"Vendedor\", type text}, {\"URL Foto\", type text}, {\"Gerente\", type text}, {\"URL Foto Corpo\", type text}})",
                "in",
                "    TipagemDados"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fMetas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "2ca1ce36-471a-4ea5-ad7b-5ed6ef1395f7",
            "sourceColumn": "Data",
            "summarizeBy": "none"
          },
          {
            "name": "Id Vendedor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "049a2ede-a2b9-4ecd-9acc-4d401f3bf3be",
            "sourceColumn": "Id Vendedor",
            "summarizeBy": "none"
          },
          {
            "name": "Valor Meta",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "6a697f6e-26e3-4e7e-a9f7-ff0a67cb6fee",
            "sourceColumn": "Valor Meta",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "c9b52119-f323-474f-8167-8d638ae40b05",
        "partitions": [
          {
            "name": "fMetas-fd5e8097-ba6d-4513-950c-25f26199ee4e",
            "mode": "import",
            "queryGroup": "Fatos",
            "source": {
              "expression": [
                "let",
                "    Fonte = Folder.Files(Caminho_Meta),",
                "    LinhasContendoArquivosExcel = Table.SelectRows(Fonte, each ([Extension] = \".xlsx\")),",
                "    ExcluirArquivosAbertos = Table.SelectRows(LinhasContendoArquivosExcel, each not Text.StartsWith([Name], \"~\")),",
                "    PermancerColunas_Content_Name = Table.SelectColumns(ExcluirArquivosAbertos,{\"Content\", \"Name\"}),",
                "    ColunaExtracaoAdicionada = Table.AddColumn(PermancerColunas_Content_Name, \"Extração\", each Excel.Workbook([Content])),",
                "    ColunaContentRemovida = Table.RemoveColumns(ColunaExtracaoAdicionada,{\"Content\"}),",
                "    CampoDadosExtracao = Table.ExpandTableColumn(ColunaContentRemovida, \"Extração\", {\"Data\"}, {\"Data\"}),",
                "    ColunaDataExpandida = Table.ExpandTableColumn(CampoDadosExtracao, \"Data\", {\"Column1\", \"Column2\", \"Column3\", \"Column4\", \"Column5\", \"Column6\", \"Column7\", \"Column8\", \"Column9\", \"Column10\", \"Column11\", \"Column12\", \"Column13\", \"Column14\", \"Column15\"}, {\"Column1\", \"Column2\", \"Column3\", \"Column4\", \"Column5\", \"Column6\", \"Column7\", \"Column8\", \"Column9\", \"Column10\", \"Column11\", \"Column12\", \"Column13\", \"Column14\", \"Column15\"}),",
                "    CabecalhoPromovido = Table.PromoteHeaders(ColunaDataExpandida, [PromoteAllScalars=true]),",
                "    RemoverLinhasCabecalhos = Table.SelectRows(CabecalhoPromovido, each ([Id Vendedor] <> null and [Id Vendedor] <> \"Id Vendedor\")),",
                "    RemoverColunaVazia = Table.RemoveColumns(RemoverLinhasCabecalhos,{\"Vendedor\", \"Column16\"}),",
                "    UnpivotarColunas_Meses_Valor = Table.UnpivotOtherColumns(RemoverColunaVazia, {\"Meta 2018.xlsx\", \"Id Vendedor\"}, \"Mes\", \"Valor Meta\"),",
                "    ExtrairAno = Table.TransformColumns(UnpivotarColunas_Meses_Valor, {{\"Meta 2018.xlsx\", each Text.BetweenDelimiters(_, \" \", \".x\"), type text}}),",
                "    MesclarAno_Meses = Table.CombineColumns(ExtrairAno,{\"Mes\", \"Meta 2018.xlsx\"},Combiner.CombineTextByDelimiter(\"-\", QuoteStyle.None),\"Data\"),",
                "    TipagemDados = Table.TransformColumnTypes(MesclarAno_Meses,{{\"Data\", type date}, {\"Id Vendedor\", Int64.Type}, {\"Valor Meta\", Currency.Type}})",
                "in",
                "    TipagemDados"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dCalendario",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e685d16a-2d74-45ca-8f91-6b8e085d7827",
            "sourceColumn": "Ano",
            "summarizeBy": "sum"
          },
          {
            "name": "Nome do Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "b0683ab6-bd25-4140-ac0d-562fbfbaa49c",
            "sortByColumn": "Mês",
            "sourceColumn": "Nome do Mês",
            "summarizeBy": "none"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1b08e45e-32d0-4bf6-a88d-6ef3fe812644",
            "sourceColumn": "Mês",
            "summarizeBy": "sum"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8d4e56cc-a822-49d4-96bb-cf63fc32004a",
            "sourceColumn": "Dia",
            "summarizeBy": "sum"
          },
          {
            "name": "Semestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9fcb30e5-2297-458f-a629-ae32ea5aa0aa",
            "sourceColumn": "Semestre",
            "summarizeBy": "none"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d1889e7e-45ab-4773-8ad8-74eb51ad8a01",
            "sourceColumn": "Trimestre",
            "summarizeBy": "none"
          },
          {
            "name": "Mes Abreviado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "a11d7992-ada8-4f21-a470-50e0ea173b5e",
            "sortByColumn": "Mês",
            "sourceColumn": "Mes Abreviado",
            "summarizeBy": "none"
          },
          {
            "name": "Mes-Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "3e1ebe06-bd3a-4e26-a647-f89f593f6c83",
            "sortByColumn": "Mes Ano Classificação",
            "sourceColumn": "Mes-Ano",
            "summarizeBy": "none"
          },
          {
            "name": "Mes Ano Classificação",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6bbb9b64-c988-4299-b0bc-769d46933278",
            "sourceColumn": "Mes Ano Classificação",
            "summarizeBy": "sum"
          },
          {
            "name": "Datas com Venda",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "expression": [
              "",
              "   dCalendario[Id Data] <= MAX(fVendas[Data Pedido])"
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "lineageTag": "d63afdaa-3d86-4471-a6ea-3dec8accb14b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Id Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "3a15f3ef-7e05-497d-8cdb-9c8bb0b4ade2",
            "sourceColumn": "Id Data",
            "summarizeBy": "none"
          },
          {
            "name": "MesPriLetra",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "LEFT( dCalendario[Mes Abreviado] )",
            "isDataTypeInferred": true,
            "lineageTag": "17607a00-4339-4f3f-85b6-9d853bb052f8",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Data",
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "de187990-0cce-4293-89d6-36caed74ff37",
                "ordinal": 0
              },
              {
                "name": "Mês",
                "column": "Mes Abreviado",
                "lineageTag": "4f2f0ffe-8e03-4d57-bb75-e2e0be2710fe",
                "ordinal": 1
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "e2c8a711-3907-491b-a6b2-0b741b61e75a",
                "ordinal": 2
              }
            ],
            "lineageTag": "438339a9-4afa-4472-8426-f68cd1439e07"
          }
        ],
        "lineageTag": "9205a3a9-0c85-4cbc-8b36-d833f354a3b7",
        "partitions": [
          {
            "name": "dCalendario-0195bc19-d31b-4cad-ae3d-1c98e2e5f713",
            "mode": "import",
            "queryGroup": "Dimensões",
            "source": {
              "expression": [
                "let",
                "        ",
                "    Fonte = List.Dates(#date(2018, 1, 1), 1461 , #duration(1, 0, 0, 0)),",
                "    ConverterListaParaTabela = Table.FromList(Fonte, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    ",
                "    ColunaData = Table.TransformColumnTypes(Table.RenameColumns(ConverterListaParaTabela,{{\"Column1\", \"Data\"}}),{{\"Data\", type date}}),",
                "    ColunaAno = Table.AddColumn(ColunaData, \"Ano\", each Date.Year([Data]), Int64.Type),",
                "    ColunaNomeMes = Table.AddColumn(ColunaAno, \"Nome do Mês\", each Date.MonthName([Data]), type text),",
                "    PriMaiusculaNomeMes = Table.TransformColumns(ColunaNomeMes,{{\"Nome do Mês\", Text.Proper, type text}}),",
                "    ColunaNomeMesAbreviado = Table.AddColumn(PriMaiusculaNomeMes, \"Mes Abreviado\", each Text.Start([Nome do Mês], 3), type text),",
                "    ColunaNumeroMes = Table.AddColumn(ColunaNomeMesAbreviado, \"Mês\", each Date.Month([Data]), Int64.Type),",
                "    ColunaDia = Table.AddColumn(ColunaNumeroMes, \"Dia\", each Date.Day([Data]), Int64.Type),",
                "    ColunaSemestre = Table.AddColumn(ColunaDia, \"Semestre\", each if [Mês] <= 6 then \"S1\" else \"S2\", type text),",
                "    ColunaTrimestre = Table.AddColumn(ColunaSemestre, \"Trimestre\", each if [Mês] <= 3 then \"T1\" else if [Mês] <= 6 then \"T2\" else if [Mês] <= 9 then \"T3\" else \"T4\", type text),",
                "    ColunaMesAno = Table.AddColumn(ColunaTrimestre, \"Mes-Ano\", each Text.Combine({[Mes Abreviado], \"-\", Text.From([Ano], \"pt-BR\")}), type text),",
                "    ColunaMesAnoClassificacao = Table.AddColumn(ColunaMesAno, \"Mes Ano Classificação\", each [Ano] * 100 + [Mês], Int64.Type ),",
                "    ColunaDataRenomeada = Table.RenameColumns(ColunaMesAnoClassificacao,{{\"Data\", \"Id Data\"}})",
                "in",
                "    ColunaDataRenomeada"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Medidas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "5d2fdeda-57d0-4fb6-a1b9-209cd3522441",
        "measures": [
          {
            "name": "Qtde Vendas",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "_Principais",
            "expression": "DISTINCTCOUNT(fVendas[Num Venda])",
            "formatString": "#,0",
            "lineageTag": "c6e2dfed-b1f9-4897-983b-d5594124b063"
          },
          {
            "name": "Positivação Clientes",
            "displayFolder": "_Principais",
            "expression": [
              "",
              "// Refere-se a Qtde de clientes que efetuaram compras ",
              "        DISTINCTCOUNT(fVendas[Id Cliente])",
              "",
              "",
              "",
              ""
            ],
            "formatString": "0",
            "lineageTag": "a8cec11c-cf82-487e-b973-012198c81a2d"
          },
          {
            "name": "Positivação Produtos",
            "displayFolder": "_Principais",
            "expression": "DISTINCTCOUNT(fVendas[Id Produto])",
            "formatString": "0",
            "lineageTag": "c2012781-389d-45e0-893e-ae783dfc4007"
          },
          {
            "name": "Faturamento",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "_Principais",
            "expression": [
              "",
              "    CALCULATE(",
              "        SUMX(",
              "            fVendas,",
              "            fVendas[Qtde] * fVendas[Valor Unit]",
              "        ),",
              "        dStatus[Id Status] = 1",
              "    )"
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "e65bb807-44fc-4cbc-983f-0ebaf546d84f"
          },
          {
            "name": "Custo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "_Principais",
            "expression": [
              "",
              "    CALCULATE(",
              "        SUMX(",
              "            fVendas,",
              "            fVendas[Qtde] * fVendas[Custo Unit]",
              "        ),",
              "        dStatus[Id Status] = 1 ",
              "    )"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "84d6ec66-1349-4b83-be22-0e27dc277249"
          },
          {
            "name": "Despesa",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "_Principais",
            "expression": [
              "",
              "    CALCULATE(",
              "        SUMX(",
              "            fVendas,",
              "            fVendas[Qtde] * fVendas[Despesa Unit]",
              "        ),",
              "        dStatus[Id Status] = 1 ",
              "    )"
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "c53f0e5b-284f-461b-a91d-e160c2cf2d72"
          },
          {
            "name": "Impostos",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "_Principais",
            "expression": [
              "",
              "    CALCULATE(",
              "        SUMX(",
              "            fVendas,",
              "            fVendas[Qtde] * fVendas[Impostos Unit]",
              "        ),",
              "        dStatus[Id Status] = 1 ",
              "    )"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "ac65b685-7f01-4b6e-af8b-5a1abfac4c7f"
          },
          {
            "name": "Comissao",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "_Principais",
            "expression": [
              "",
              "    CALCULATE(",
              "           SUMX(",
              "            fVendas,",
              "            fVendas[Qtde] * fVendas[Comissão Unit]",
              "        ),",
              "        dStatus[Id Status] = 1 ",
              "    )"
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "e2a5d29f-47dc-4b3f-8806-6aed1cffa86a"
          },
          {
            "name": "Abatimento",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "_Principais",
            "expression": [
              "",
              "    [Custo] + [Despesa] + [Impostos] + [Comissao]"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "ffded7eb-d67b-4fda-b5ef-fcc413ba4754"
          },
          {
            "name": "Resultado",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "_Principais",
            "expression": [
              "",
              "    [Faturamento] - [Abatimento]"
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "1578b7a7-9512-464d-9cf7-eba4bfc015c7"
          },
          {
            "name": "Margem Percentual",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "_Principais",
            "expression": [
              "",
              "",
              "    DIVIDE([Resultado],[Faturamento])",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f7c93f03-2660-47dc-a1ba-3ab292788714"
          },
          {
            "name": "Meta",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "_Principais",
            "expression": "SUM(fMetas[Valor Meta])",
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "6ccbb42e-fabc-476a-b8ab-1da1af42d907"
          },
          {
            "name": "Porcentagem Meta",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "_Principais",
            "expression": [
              "DIVIDE([Faturamento],[Meta],0)",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a06c30a5-1c72-4558-b5a4-c458ca60113c"
          },
          {
            "name": "Circulo Farol",
            "displayFolder": "Tooltips",
            "expression": "UNICHAR(11044)",
            "lineageTag": "df64e01b-3113-48e7-9bb7-35ae25843680"
          },
          {
            "name": "Faturamento Acumulado",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "_Temporais",
            "expression": [
              "",
              "    CALCULATE(",
              "        [Faturamento],",
              "        CALCULATETABLE(",
              "            DATESYTD(dCalendario[Id Data]),",
              "            dCalendario[Datas com Venda] = TRUE()",
              "        )",
              "    )"
            ],
            "lineageTag": "3e353a4d-89d7-48d9-89c2-2390d17f76ab"
          },
          {
            "name": "Faturamento LY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "_Temporais",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    [Faturamento],",
              "    CALCULATETABLE(",
              "        SAMEPERIODLASTYEAR( dCalendario[Id Data] ),",
              "        dCalendario[Datas com Venda] = TRUE() ",
              "    )",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "adc6447c-2e95-48a3-abe7-4a797e257a94"
          },
          {
            "name": "Faturamento YoY %",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "_Temporais",
            "expression": [
              "",
              "",
              "VAR vAtual = [Faturamento] ",
              "VAR vAnterior = [Faturamento LY]",
              "",
              "VAR vResultado = ",
              "    DIVIDE(",
              "        vAtual - vAnterior,",
              "        vAnterior",
              "    ) ",
              "",
              "RETURN",
              "    vResultado "
            ],
            "lineageTag": "3f4b893d-adee-4640-8752-e155e6e8519a"
          },
          {
            "name": "Margem LY",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "_Temporais",
            "expression": [
              "",
              "CALCULATE(",
              "    [Margem Percentual],",
              "    CALCULATETABLE(",
              "        SAMEPERIODLASTYEAR( dCalendario[Id Data] ),",
              "        dCalendario[Datas com Venda] = TRUE() ",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "52bcce5b-b2f7-4f68-8f1a-ec461ddf5c1e"
          },
          {
            "name": "Margem YoY %",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "_Temporais",
            "expression": [
              "",
              "VAR vAtual = [Margem Percentual] ",
              "VAR vAnterior = [Margem LY]",
              "",
              "VAR vResultado = ",
              "    DIVIDE(",
              "        vAtual - vAnterior,",
              "        vAnterior",
              "    ) ",
              "",
              "RETURN",
              "    vResultado "
            ],
            "lineageTag": "25be8cc5-3e67-4582-bf97-5a733a622ae2"
          },
          {
            "name": "Resultado LY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "_Temporais",
            "expression": [
              "",
              "CALCULATE(",
              "    [Resultado],",
              "    CALCULATETABLE(",
              "        SAMEPERIODLASTYEAR( dCalendario[Id Data] ),",
              "        dCalendario[Datas com Venda] = TRUE() ",
              "    )",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "44f36d9f-2ffd-48ca-9f8e-27d81909ce70"
          },
          {
            "name": "Resultado YoY %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "_Temporais",
            "expression": [
              "",
              "VAR vAtual = [Resultado] ",
              "VAR vAnterior = [Resultado LY]",
              "",
              "VAR vResultado = ",
              "    DIVIDE(",
              "        vAtual - vAnterior,",
              "        vAnterior",
              "    ) ",
              "",
              "RETURN",
              "    vResultado "
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "6499ef05-8be9-453e-82ad-c3afdb8ceac6"
          },
          {
            "name": "Meta Cor",
            "displayFolder": "_Principais",
            "expression": [
              "",
              "",
              "Var vPorcentagem = [Porcentagem Meta] ",
              "Return",
              "",
              "    SWITCH(",
              "        TRUE(),",
              "        vPorcentagem >= 1, \"#53A365\",",
              "        vPorcentagem >= 0.8, \"#E1A55D\",",
              "        \"#CF6F45\"",
              "    )"
            ],
            "lineageTag": "653c6938-ab0e-4235-a2bc-4cdabcddcf60"
          },
          {
            "name": "Maior Valor",
            "displayFolder": "Bônus 5.9 Deneb",
            "expression": [
              "",
              "",
              "",
              "VAR vTabela = ",
              "    FILTER(",
              "        ALLSELECTED( dCalendario[Mes Abreviado], dCalendario[Mês]), ",
              "        not ISBLANK( [Faturamento] )",
              "    )",
              "",
              "VAR vMaior_valor = ",
              "    MAXX( vTabela, [Faturamento] ) ",
              "",
              "VAR vCheck = ",
              "    IF( [Faturamento] = vMaior_valor, \"s\" ) ",
              "",
              "RETURN",
              "    vCheck  ",
              ""
            ],
            "lineageTag": "212667bb-c97e-4ca6-9b66-ab5def382946"
          },
          {
            "name": "Menor Valor",
            "displayFolder": "Bônus 5.9 Deneb",
            "expression": [
              "",
              "",
              "",
              "VAR vTabela = ",
              "    FILTER(",
              "        ALLSELECTED( dCalendario[Mes Abreviado], dCalendario[Mês]), ",
              "        not ISBLANK( [Faturamento] )",
              "    )",
              "",
              "VAR vMenor_valor = ",
              "    MINX( vTabela, [Faturamento] ) ",
              "",
              "VAR vCheck = ",
              "    IF( [Faturamento] = vMenor_valor, \"s\" ) ",
              "",
              "RETURN",
              "    vCheck  ",
              ""
            ],
            "lineageTag": "60ce1657-bb26-41b3-8b3c-4b90a476fedf"
          },
          {
            "name": "Ultimo mes ?",
            "displayFolder": "Bônus 5.9 Deneb",
            "expression": [
              "",
              "",
              "VAR vTabela =",
              "    ALLSELECTED( dCalendario[Mes Abreviado], dCalendario[Mês] )",
              "",
              "VAR vUltimo_mes = ",
              "    CALCULATE(",
              "        MONTH( MAX( fVendas[Data Pedido] ) ),",
              "        vTabela",
              "    )",
              "",
              "VAR vUltimo_mes_v2 = ",
              "    MAXX(",
              "        FILTER( vTabela, NOT ISBLANK( [Faturamento] ) ), ",
              "        dCalendario[Mês]",
              "    )",
              "",
              "VAR vMes_contexto = ",
              "    MAX( dCalendario[Mês] ) ",
              "",
              "VAR vResultado = ",
              "    IF( vMes_contexto = vUltimo_mes, \"s\" )  ",
              "",
              "RETURN ",
              "    vResultado ",
              ""
            ],
            "lineageTag": "904540c3-28dd-4a8f-b27b-8ace78a84fef"
          },
          {
            "name": "Faturamento Fixo",
            "displayFolder": "Bônus 5.9 Deneb\\Gráfico Rosca",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    [Faturamento], ",
              "    ALL( dVendedores[Vendedor], dVendedores[URL Foto] ) ",
              ")"
            ],
            "formatString": "#,0.00",
            "lineageTag": "d4cf9a8d-bdd4-426b-b146-cc187df998e8"
          },
          {
            "name": "Margem Contribuição",
            "displayFolder": "Bônus 5.9 Deneb\\Gráfico Rosca",
            "expression": [
              "",
              "    DIVIDE( [Faturamento], [Faturamento Fixo] ) "
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "dbe542e9-c732-494b-b502-9a68c3ad0644"
          },
          {
            "name": "Faturamento ACC",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Bônus 5.9 Deneb\\Gráfico Rosca",
            "expression": [
              "",
              "",
              "VAR vVendedor_contexto = ",
              "    SELECTEDVALUE( dVendedores[Vendedor] ) ",
              "",
              "VAR vResultado = ",
              "    CALCULATE(",
              "        [Faturamento],",
              "        FILTER(",
              "            ALL(dVendedores[Vendedor], dVendedores[URL Foto]), ",
              "            dVendedores[Vendedor] <= vVendedor_contexto",
              "        )",
              "    )",
              "",
              "RETURN ",
              "    vResultado  "
            ],
            "lineageTag": "e0685aca-f107-4d57-b27a-88f660fe6dd7"
          },
          {
            "name": "Eixo_x",
            "displayFolder": "Bônus 5.9 Deneb\\Gráfico Rosca",
            "expression": [
              "",
              "-- SIN( 2*PI() * ( [Acumulado]-[Faturamento] / 2) / [Fixo] )",
              "",
              "SIN(",
              "    2 * PI() * ",
              "    ( [Faturamento ACC] - [Faturamento] / 2 ) / ",
              "    [Faturamento Fixo]",
              ")"
            ],
            "formatString": "0.0000%;-0.0000%;0.0000%",
            "lineageTag": "8548703f-988f-4b2d-8002-136e69fa82b3"
          },
          {
            "name": "Eixo_y",
            "displayFolder": "Bônus 5.9 Deneb\\Gráfico Rosca",
            "expression": [
              "",
              "-- SIN( 2*PI() * ( [Acumulado]-[Faturamento] / 2) / [Fixo] )",
              "",
              "COS(",
              "    2 * PI() * ",
              "    ( [Faturamento ACC] - [Faturamento] / 2 ) / ",
              "    [Faturamento Fixo]",
              ")"
            ],
            "formatString": "0.00",
            "lineageTag": "4beb52a5-0137-4aee-8b9b-530ebf423418"
          },
          {
            "name": "Variacao Cor",
            "displayFolder": "Bônus 5.9 Deneb",
            "expression": [
              "",
              "",
              "VAR vPerc_yoy = [Faturamento YoY %]",
              "",
              "RETURN ",
              "    SWITCH(",
              "        TRUE(),",
              "        vPerc_yoy > 0, \"#11c4d1\",",
              "        vPerc_yoy < 0, \"#bf5064\",",
              "        \"#0000\"",
              "    )"
            ],
            "lineageTag": "d9e5d4b4-170e-4f52-84bd-0bdf5f7996e6"
          },
          {
            "name": "Faturamento Cartao Subtitulo",
            "displayFolder": "Cartões\\Faturamento",
            "expression": [
              "",
              "",
              "VAR vMelhor_mes_tabela = ",
              "    TOPN( ",
              "        1,",
              "        ALL( dCalendario[Mes Abreviado], dCalendario[Nome do Mês], dCalendario[Mês] ),",
              "        [Faturamento],",
              "        DESC",
              "    )",
              "",
              "VAR vMelhor_mes_escalar = ",
              "    MAXX( vMelhor_mes_tabela, dCalendario[Mes Abreviado] )",
              "",
              "RETURN ",
              "    \"(\" & vMelhor_mes_escalar & \")\" & \" melhor mês\" "
            ],
            "lineageTag": "2f82aa57-297c-4a65-8227-bf0169ccd9e7"
          },
          {
            "name": "Faturamento Cartao Titulo",
            "displayFolder": "Cartões\\Faturamento",
            "expression": [
              "",
              "",
              "VAR vPerc_ano_anterior = ",
              "    [Faturamento YoY %] ",
              "",
              "VAR vPerc_ano_anterior_formatado = ",
              "    FORMAT( vPerc_ano_anterior + 0 , \"⮝ +0.0% vs Ano Anterior; ⮟ -0.0% vs Ano Anterior ; não houve variação\" )",
              "",
              "RETURN ",
              "    vPerc_ano_anterior_formatado "
            ],
            "lineageTag": "928a5e04-2a4f-4162-97b0-b0cd211f6376"
          },
          {
            "name": "Faturamento Cartao Titulo Form. Cond.",
            "displayFolder": "Cartões\\Faturamento",
            "expression": [
              "",
              "",
              "VAR vPerc_ano_anterior = ",
              "    [Faturamento YoY %] ",
              "",
              "",
              "",
              "RETURN ",
              "    SWITCH(",
              "        TRUE(),",
              "        vPerc_ano_anterior > 0, \"#53A365\",",
              "        vPerc_ano_anterior < 0, \"#CF6F45\",",
              "        \"#958FAB\"",
              "    )"
            ],
            "lineageTag": "44a73857-f152-4c79-b50a-2153e49962e1"
          },
          {
            "name": "Resultado Cartão Subtitulo",
            "displayFolder": "Cartões\\Resultado",
            "expression": [
              "",
              "",
              "VAR vMelhor_mes_tabela = ",
              "    TOPN( ",
              "        1, ",
              "        ALL( dCalendario[Mes Abreviado], dCalendario[Nome do Mês], dCalendario[Mês]), ",
              "        [Resultado],",
              "        DESC ",
              "    )",
              "",
              "VAR vMelhor_mes_escalar = ",
              "    MAXX( vMelhor_mes_tabela, dCalendario[Mes Abreviado]  )",
              "",
              "",
              "RETURN ",
              "    \"(\" & vMelhor_mes_escalar & \")\" & \" melhor mês\""
            ],
            "lineageTag": "95ce681a-1e30-40e6-ab8e-90f02e711f1e"
          },
          {
            "name": "Resultado Cartão Título",
            "displayFolder": "Cartões\\Resultado",
            "expression": [
              "",
              "",
              "VAR vPerc_yoy = [Resultado YoY %] ",
              "",
              "VAR vPerc_formatado = ",
              "    FORMAT( vPerc_yoy + 0 , \"⮝ +0.0% vs Ano Anterior; ⮟ -0.0% vs Ano Anterior ; não houve variação\" )",
              "",
              "VAR vIcone = ",
              "    SWITCH(",
              "        TRUE(),",
              "        vPerc_yoy > 0, \"▲ \",",
              "        vPerc_yoy < 0, \"▼ \"",
              "    )",
              "",
              "RETURN ",
              "    vPerc_formatado  "
            ],
            "lineageTag": "aeb690d0-8aad-4c17-b7c8-a4c241e86df3"
          },
          {
            "name": "Resultado Cartão Título Form. Cond.",
            "displayFolder": "Cartões\\Resultado",
            "expression": [
              "",
              "",
              "VAR vPerc_yoy = [Resultado YoY %] ",
              "",
              "RETURN ",
              "    SWITCH( ",
              "        TRUE(), ",
              "        vPerc_yoy > 0, \"#53A365\",",
              "        vPerc_yoy < 0, \"#CF6F45\",",
              "        \"#958fab\"",
              "    )"
            ],
            "lineageTag": "92fd81b8-9e02-44f0-9922-31c85b9e3c4e"
          },
          {
            "name": "Margem Cartão Subtitulo",
            "displayFolder": "Cartões\\Margem",
            "expression": [
              "",
              "",
              "VAR vMelhor_mes_tabela = ",
              "    TOPN( ",
              "        1, ",
              "        ALL( dCalendario[Mes Abreviado], dCalendario[Nome do Mês], dCalendario[Mês]),",
              "        [Margem Percentual],",
              "        DESC ",
              "    )",
              "",
              "VAR vMelhor_mes_escalar = ",
              "    MAXX( vMelhor_mes_tabela, dCalendario[Mes Abreviado]  )",
              "",
              "",
              "RETURN ",
              "    \"(\" & vMelhor_mes_escalar & \")\" & \" melhor mês\""
            ],
            "lineageTag": "109f4a54-0d50-4267-a22b-9664eeac3215"
          },
          {
            "name": "Margem Cartão Título",
            "displayFolder": "Cartões\\Margem",
            "expression": [
              "",
              "",
              "VAR vPerc_yoy = [Margem YoY %] ",
              "",
              "VAR vPerc_formatado = ",
              "    FORMAT( vPerc_yoy + 0 , \"⮝ +0.0% vs Ano Anterior; ⮟ -0.0% vs Ano Anterior ; não houve variação\" )",
              "",
              "",
              "RETURN ",
              "     vPerc_formatado "
            ],
            "lineageTag": "614f6820-6e8b-44ab-a2f3-9d7dbafd1894"
          },
          {
            "name": "Margem Cartão Título Form. Cond.",
            "displayFolder": "Cartões\\Margem",
            "expression": [
              "",
              "",
              "VAR vPerc_yoy = [Margem YoY %] ",
              "",
              "RETURN ",
              "    SWITCH( ",
              "        TRUE(), ",
              "        vPerc_yoy > 0, \"#53A365\",",
              "        vPerc_yoy < 0, \"#CF6F45\",",
              "        \"#958fab\"",
              "    )"
            ],
            "lineageTag": "66f410ca-dea8-4c5a-a5be-198fa8d12131"
          },
          {
            "name": "001 Acumulado",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "displayFolder": "Gráfico Pareto",
            "expression": [
              "",
              "",
              "VAR vTabela = ",
              "    WINDOW(",
              "        1,ABS,",
              "        0, REL,",
              "        FILTER(",
              "            ALLSELECTED( dProdutos[Subcategoria] ),",
              "            [Faturamento]",
              "        ),",
              "        ORDERBY( [Faturamento], DESC )",
              "    )",
              "",
              "VAR vAcumulado = ",
              "    CALCULATE(",
              "        [Faturamento],",
              "        vTabela",
              "    )",
              "",
              "RETURN",
              "    vAcumulado  "
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "29edea5a-14e1-4efb-82a3-2f7b91fe2307"
          },
          {
            "name": "002 Percentual",
            "displayFolder": "Gráfico Pareto",
            "expression": [
              "",
              "",
              "VAR vTabela = ",
              "    WINDOW(",
              "        1,ABS,",
              "        -1, ABS,",
              "        FILTER(",
              "            ALL( dProdutos[Subcategoria] ),",
              "            [Faturamento]",
              "        )",
              "    )",
              "",
              "VAR vValorFixo = ",
              "    CALCULATE(",
              "        [Faturamento],",
              "        vTabela",
              "    )",
              "",
              "VAR vPercentual = ",
              "    DIVIDE( [001 Acumulado], vValorFixo )",
              "",
              "RETURN",
              "    vPercentual    "
            ],
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "lineageTag": "08f04142-9ebc-4977-9281-6c829c1bc3df"
          },
          {
            "name": "003 Destaque",
            "displayFolder": "Gráfico Pareto",
            "expression": [
              "",
              "",
              "VAR vCorte = ",
              "    [Pareto Corte] ",
              "",
              "VAR vTabela = ",
              "    WINDOW(",
              "        1,ABS,",
              "        -1, ABS,",
              "        FILTER(",
              "            ALLSELECTED( dProdutos[Subcategoria] ),",
              "            [Faturamento] && ",
              "            [002 Percentual] <= vCorte ",
              "        )",
              "    )",
              "",
              "VAR vUltimoContexto = ",
              "    INDEX(",
              "        -1,",
              "        vTabela,",
              "        ORDERBY( [Faturamento], DESC )",
              "    )",
              "",
              "VAR vContexto = ",
              "    SELECTEDVALUE( dProdutos[Subcategoria] ) ",
              "",
              "VAR vResultado = ",
              "-- Precisa Retornar o Valor 1, para funcionar no gráfico que eu vou disponibilizar o template ",
              "    IF(",
              "        vContexto = vUltimoContexto,",
              "        1",
              "    )",
              "",
              "",
              "",
              "RETURN",
              "    vResultado       "
            ],
            "formatString": "0",
            "lineageTag": "bf4e5235-7624-4f4e-a468-c252bbf86307"
          },
          {
            "name": "004 Classe ABC",
            "displayFolder": "Gráfico Pareto",
            "expression": [
              "",
              "",
              "VAR vValor = [Faturamento]",
              "",
              "VAR vPercentual = [002 Percentual]",
              "",
              "VAR vCorte = [Pareto Corte] ",
              "",
              "VAR vClassificacao = ",
              "    SWITCH(",
              "        TRUE(),",
              "        ISBLANK( vValor ),                              BLANK(),",
              "        vPercentual <= vCorte,                          \"A\", ",
              "        vPercentual > vCorte && vPercentual <= 0.92,    \"B\",",
              "                                                        \"C\"",
              "    )",
              "",
              "VAR vResultado = ",
              "    IF(",
              "        ISINSCOPE( dProdutos[Subcategoria] ),",
              "         vClassificacao",
              "    )",
              "",
              "RETURN",
              "    vResultado  ",
              "",
              ""
            ],
            "lineageTag": "59089545-efe6-49cb-89ca-bc10087e121e"
          },
          {
            "name": "005 Classe ABC Form. Cond",
            "displayFolder": "Gráfico Pareto",
            "expression": [
              "",
              "",
              "",
              "--------------------------",
              "-- Cores",
              "--------------------------",
              "",
              "VAR vCorA = \"#7A8B9F\" ",
              "",
              "VAR vCorB = \"#E1A55D\" ",
              "",
              "VAR vCorC = \"#CF6F45\" ",
              "",
              "",
              "",
              "--------------------------",
              "-- Medidas",
              "--------------------------",
              "",
              "VAR vValor = [Faturamento]",
              "",
              "VAR vPercentual = [002 Percentual]",
              "",
              "VAR vCorte = [Pareto Corte] ",
              "",
              "VAR vClassificacao = ",
              "    SWITCH(",
              "        TRUE(),",
              "        ISBLANK( vValor ),                              BLANK(),",
              "        vPercentual <= vCorte,                          vCorA, ",
              "        vPercentual > vCorte && vPercentual <= 0.92,    vCorB,",
              "                                                        vCorC",
              "    )",
              "",
              "VAR vResultado = ",
              "    IF(",
              "        ISINSCOPE( dProdutos[Subcategoria] ),",
              "         vClassificacao",
              "    )",
              "",
              "RETURN",
              "    vResultado  ",
              "",
              ""
            ],
            "lineageTag": "fcc7dd4e-143c-4f0f-9a02-dfc5e7a405bb"
          },
          {
            "name": "006 Rotulos",
            "displayFolder": "Gráfico Pareto",
            "expression": [
              "",
              "",
              "VAR vSubcategoria = ",
              "    SELECTEDVALUE( dProdutos[Subcategoria] )",
              "",
              "VAR vValor = ",
              "    [Faturamento] ",
              "",
              "VAR vValorFormatado = ",
              "    SWITCH(",
              "        TRUE(),",
              "        ABS( vValor ) >= 1e9,  FORMAT( vValor, \"R$ #,0,,,.00 Bi\" ),",
              "        ABS( vValor ) >= 1e6,  FORMAT( vValor, \"R$ #,0,,.00 Mi\" ),",
              "        ABS( vValor ) >= 1e3,  FORMAT( vValor, \"R$ #,0,.00 K\" ),",
              "        FORMAT( vValor, \"R$ #,0\" )",
              "    )",
              "  ",
              "",
              "VAR vRotulo = ",
              "    IF(",
              "        vValor,",
              "        vSubcategoria  & \" | \" & vValorFormatado ",
              "    )",
              "",
              "RETURN",
              "    vRotulo    "
            ],
            "lineageTag": "6ba5de60-6226-4386-a7d7-25401a0d68ff"
          },
          {
            "name": "007 Subtitulo",
            "displayFolder": "Gráfico Pareto",
            "expression": [
              "",
              "",
              "VAR vCorte = ",
              "    [Pareto Corte] ",
              "",
              "VAR vTabela = ",
              "    WINDOW(",
              "        1,ABS,",
              "        -1, ABS,",
              "        FILTER(",
              "            ALLSELECTED( dProdutos[Subcategoria] ),",
              "            [Faturamento] && ",
              "            [002 Percentual] <= vCorte ",
              "        )",
              "    )",
              "",
              "VAR vQtdeProdutos = ",
              "    COUNTROWS( vTabela )  ",
              "",
              "VAR vPercentual = ",
              "    CALCULATE( [002 Percentual], vTabela )",
              " ",
              "VAR vPercentualFormatado = ",
              "    FORMAT( vPercentual, \"#.0%\" )",
              "",
              "VAR vValor = ",
              "    CALCULATE( [Faturamento], vTabela ) ",
              "",
              "VAR vValorFormatado = ",
              "    SWITCH(",
              "        TRUE(),",
              "        ABS( vValor ) >= 1e9,  FORMAT( vValor, \"R$ #,0,,,.00 Bi\" ),",
              "        ABS( vValor ) >= 1e6,  FORMAT( vValor, \"R$ #,0,,.00 Mi\" ),",
              "        ABS( vValor ) >= 1e3,  FORMAT( vValor, \"R$ #,0,.00 K\" ),",
              "        FORMAT( vValor, \"R$ #,0\" )",
              "    )",
              "",
              "",
              "VAR vSubtitulo = ",
              "    vQtdeProdutos & \" produtos representam \" ",
              "    & vPercentualFormatado & \" do faturamento com total de \" ",
              "    & vValorFormatado  ",
              "",
              "RETURN",
              "    vSubtitulo  "
            ],
            "lineageTag": "2cb8b625-a774-45c7-9812-f33c7d6b9901"
          },
          {
            "name": "Semaforo Animado",
            "displayFolder": "Tooltips",
            "expression": [
              "",
              "",
              "/* ",
              "",
              "Link da aula com todo passo a passo para contrução dessa medida (copiar a URL no seu navegador )",
              "https://powerbidashboardsanimados.club.hotmart.com/lesson/ROxpMQYxOD?role=OWNER&classHash=wx7W8RbYO2",
              "",
              "*/",
              "",
              "VAR vPorcentagem = [Porcentagem Meta]",
              "",
              "VAR vPos_circ_meta = ",
              "    SWITCH(",
              "        TRUE(),",
              "        vPorcentagem >= 1, 242,",
              "        vPorcentagem >= 0.81, 145,",
              "        48",
              "    )",
              "",
              "",
              "",
              "---------------------------------------------",
              "-- FORMATAÇÕES",
              "---------------------------------------------",
              "",
              "VAR vEstrutura_cor = \"#202831\"",
              "",
              "VAR vCirc_fundo_cor = \"#4B5661\"",
              "",
              "VAR vMeta_cor = ",
              "    SWITCH(",
              "        TRUE(),",
              "        vPorcentagem >= 1, \"#53A365\",",
              "        vPorcentagem >= 0.8, \"#E1A55D\",",
              "        \"#CF6F45\"",
              "    )",
              "",
              "VAR vAnimacao = \"on\" ",
              "-- Opções on / off ",
              "",
              "",
              "VAR vPrefixo = \"data:image/svg+xml,\"",
              "",
              "RETURN ",
              "",
              "vPrefixo & ",
              "",
              "\"",
              "<svg  viewBox='80 0 200 350' fill='none' xmlns='http://www.w3.org/2000/svg'>",
              "\t",
              "    <defs>",
              "        <style>",
              "",
              "            ",
              "",
              "            #circ_colorido {",
              "                \" & IF( vAnimacao = \"on\", \"animation\", BLANK() ) & \": blink-1 1s infinite both;",
              "            }",
              "",
              "            @keyframes blink-1 {",
              "                0%,",
              "                50%,",
              "                100% {",
              "                    opacity: 1;",
              "                }",
              "                25%,",
              "                75% {",
              "                    opacity: 0;",
              "                }",
              "            }",
              "",
              "",
              "",
              "        </style>",
              "",
              "    </defs>",
              "    ",
              "    ",
              "    <g id='semaforo'>",
              "\t\t",
              "        ",
              "        <path id='circ_fundo' fill-rule='evenodd' clip-rule='evenodd' d='M135 48C135 67.33 119.33 83 100 83C80.67 83 65 67.33 65 48C65 28.67 80.67 13 100 13C119.33 13 135 28.67 135 48ZM135 142C135 161.33 119.33 177 100 177C80.67 177 65 161.33 65 142C65 122.67 80.67 107 100 107C119.33 107 135 122.67 135 142ZM100 271C119.33 271 135 255.33 135 236C135 216.67 119.33 201 100 201C80.67 201 65 216.67 65 236C65 255.33 80.67 271 100 271Z' fill='\" & vCirc_fundo_cor & \"'/>",
              "\t\t",
              "        ",
              "        <circle id='circ_colorido' cx='100' cy='\" & vPos_circ_meta & \"' r='35' fill='\" & vMeta_cor& \"'/>",
              "\t\t",
              "        ",
              "        <path id='estrutura' fill-rule='evenodd' clip-rule='evenodd' d='M57.0048 48.2237L57.2774 91.4474L100.361 91.7209L143.444 91.9944V48.4972V5H100.088H56.7322L57.0048 48.2237ZM110.022 19.7432C121.046 22.739 130.128 35.6024 130.128 48.2227C130.128 64.9662 116.788 78.3493 100.1 78.3493C91.74 78.3493 85.1976 75.5851 79.1178 69.4866C72.3133 62.6599 69.8588 55.9118 70.5669 45.9792C71.1351 38.0198 73.1499 33.4019 78.5423 27.7016C86.9 18.8683 97.2098 16.2623 110.022 19.7432ZM20.5076 20.4558C20.7447 20.8875 27.4333 33.2657 35.3722 47.9618C43.311 62.6578 50.1939 75.1293 50.6692 75.6773C51.1444 76.2243 51.5329 63.8471 51.5329 48.1713V19.6699H35.8046C27.1545 19.6699 20.2705 20.024 20.5076 20.4558ZM149.711 47.6128C149.711 62.9806 149.891 75.3588 150.111 75.1188C150.802 74.3623 180 20.6779 180 20.1613C180 19.891 173.185 19.6699 164.856 19.6699H149.711V47.6128ZM92.1881 24.3747C80.0652 28.2779 72.2589 43.4602 76.021 55.8206C76.9036 58.7211 77.03 58.4727 77.6546 52.6257C79.3361 36.8902 90.5504 26.0775 105.322 25.9486C110.205 25.9056 111.174 25.651 109.71 24.7959C106.55 22.9528 97.2965 22.7296 92.1881 24.3747ZM56.7552 142.268V185.23H100.1H143.444V142.268V99.3063H100.1H56.7552V142.268ZM107.68 113.292C130.742 119.294 137.975 148.805 120.293 164.754C107.153 176.607 87.1768 174.742 76.4743 160.664C66.1395 147.069 68.8749 128.248 82.6658 118.073C87.0682 114.825 94.4837 112.156 99.6109 111.974C101.066 111.922 104.696 112.515 107.68 113.292ZM23.0665 119.477C24.7522 122.504 31.1202 134.173 37.2177 145.412C43.3152 156.65 49.0158 166.788 49.8858 167.94C51.3105 169.829 51.4703 167.263 51.4995 142.006L51.5329 113.976H35.767H20L23.0665 119.477ZM149.711 141.919C149.711 157.287 149.891 169.665 150.11 169.425C150.705 168.773 180 114.805 180 114.36C180 114.148 173.185 113.976 164.856 113.976H149.711V141.919ZM92.1463 118.566C79.6954 123.03 72.1837 136.915 75.9229 148.555L77.4373 153.27L77.5407 148.48C77.8843 132.552 90.048 120.367 105.788 120.184L112.633 120.104L108.978 118.691C104.308 116.887 96.98 116.833 92.1463 118.566ZM56.7552 236.55V279.489L75.8163 279.774L94.8775 280.06L95.1887 286.609C95.4927 293.01 95.4394 293.158 92.8387 293.158H90.1775V319.354V345.551H100.64H111.103L110.823 319.616L110.544 293.682L108.194 293.347C106.035 293.04 105.844 292.464 105.844 286.274V279.536H124.644H143.444V236.574V193.613H100.1H56.7552V236.55ZM113.859 209.897C120.526 213.17 127.13 220.872 128.928 227.471C132.943 242.216 126.856 256.727 113.772 263.604C106.594 267.376 94.0284 267.618 87.4452 264.112C80.8485 260.599 77.3057 257.173 74.0324 251.139C66.5134 237.281 70.8134 219.858 83.8179 211.486C93.1051 205.507 103.766 204.943 113.859 209.897ZM23.0863 213.784C24.7836 216.809 31.1484 228.48 37.2313 239.718C43.3142 250.956 49.0054 261.094 49.8785 262.247C51.3125 264.138 51.4692 261.616 51.4995 236.312L51.5329 208.282H35.767H20L23.0863 213.784ZM149.742 236.312C149.761 252.399 150.156 263.673 150.669 262.771C154.238 256.496 180 208.979 180 208.671C180 208.457 173.185 208.282 164.856 208.282H149.711L149.742 236.312ZM92.0147 212.853C83.2079 216.151 77.5177 222.652 75.4936 231.727C74.4899 236.223 74.5536 238.133 75.8487 242.39L77.4269 247.577L77.5355 242.786C77.8979 226.816 90.1054 214.61 105.788 214.538C111.263 214.512 112.238 214.276 110.662 213.357C107.501 211.515 96.3888 211.214 92.0147 212.853Z' fill='\" & vEstrutura_cor & \"'/>",
              "\t</g>",
              "</svg>",
              "",
              "\""
            ],
            "lineageTag": "4cdebc91-d1ec-4245-bcb8-f813d3bfbb55"
          }
        ],
        "partitions": [
          {
            "name": "_Medidas-332540c9-11b5-4161-9242-ae9d094a8fc8",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Coluna 1\" = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Coluna 1\", type text}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"Coluna 1\"})",
                "in",
                "    #\"Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "pParetoCorte",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "6f7bb18d33494a7fa159e382ccd9074c"
          }
        ],
        "columns": [
          {
            "name": "pParetoCorte",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "double",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "formatString": "0%;-0%;0%",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "f93ab6be-8064-4874-a144-71a11bfb6820",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "bc58c4da-37dd-4dad-a032-ddf5fdb2d5b9",
        "measures": [
          {
            "name": "Pareto Corte",
            "expression": "SELECTEDVALUE('pParetoCorte'[pParetoCorte], 0.8 )",
            "formatString": "0%;-0%;0%",
            "lineageTag": "08205c0d-9300-4465-b555-10e4a84fd9e7"
          },
          {
            "name": "Pareto Corte Texto",
            "expression": [
              "",
              "    FORMAT(",
              "        [Pareto Corte],",
              "        \"#%\"",
              "    )"
            ],
            "lineageTag": "0ff1a74b-2874-4f3f-849b-7fb24c3f3df6"
          }
        ],
        "partitions": [
          {
            "name": "pParetoCorte",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(0.3, 0.91, 0.05)",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}